import os
from fpdf import FPDF
from datetime import datetime
from pathlib import Path

from server.security import sanitize_upload_name


REPORTS_DIR = Path("reports")

class ElioReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.set_text_color(234, 179, 8) # Elio Gold
        self.cell(0, 10, 'ELIO | EXECUTIVE PROJECT REPORT', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Elio AI on {datetime.now().strftime("%Y-%m-%d")}', 0, 0, 'C')

def generate_project_report(user_name, project_title, technical_data, financial_summary):
    """
    Creates a professional PDF summary of a project.
    """
    pdf = ElioReport()
    pdf.add_page()
    
    # Project Overview
    pdf.set_font('Arial', 'B', 12)
    pdf.set_text_color(255, 255, 255)
    pdf.set_fill_color(30, 30, 36)
    pdf.cell(0, 10, f'Project: {project_title}', 0, 1, 'L', fill=True)
    pdf.ln(5)
    
    # Financials
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, 'Financial Status:', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 10, financial_summary)
    pdf.ln(5)
    
    # Technical Specs
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 10, 'Technical Specifications:', 0, 1)
    pdf.set_font('Arial', '', 10)
    pdf.multi_cell(0, 10, str(technical_data))
    
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.utcnow().strftime("%Y%m%d%H%M%S")
    base_name = sanitize_upload_name(f"report_{project_title}_{timestamp}.pdf", default="report.pdf")
    report_path = REPORTS_DIR / base_name
    pdf.output(str(report_path))
    return report_path.name
